# Generated by Django 4.1.2 on 2022-12-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_card.book', verbose_name='Book in basket')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodsinbaskets', to='basket.basket')),
            ],
        ),
    ]
