# Generated by Django 4.1.2 on 2022-12-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0002_alter_book_price'),
        ('basket', '0002_goodsinbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinbasket',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goodsinbaskets', to='product_card.book', verbose_name='Book in basket'),
        ),
        migrations.AlterField(
            model_name='goodsinbasket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_process', 'In Process'), ('done', 'Processed and delivered')], max_length=50, verbose_name='Stasuses')),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='basket.basket')),
            ],
        ),
    ]
