# Generated by Django 4.1.2 on 2022-11-16 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_book', '0002_rename_autor_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cover', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('published', models.DateField(null=True)),
                ('pages', models.IntegerField()),
                ('binding', models.CharField(max_length=40)),
                ('book_format', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('ISBN', models.CharField(max_length=40)),
                ('weight', models.IntegerField()),
                ('allowed_age', models.IntegerField(blank=True, default=0, null=True)),
                ('available', models.IntegerField()),
                ('active', models.BooleanField(default='Yes')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateField()),
                ('updated', models.DateField(default=datetime.date.today)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='reference_book.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='reference_book.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='reference_book.publisher')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='reference_book.seria')),
            ],
        ),
    ]
