# Generated by Django 4.1.2 on 2022-10-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
    ]
